### ISSUE TITLE
What is a "dabatase-cluster"?

### ISSUE THREAD

**Issue by radicaldo** [aws-samples/automatic-autoscaling-tagging-from-dabatase-cluster#1]
![image](https://github.com/user-attachments/assets/64c9b7b6-dfb7-4343-b500-356cd5cc14e3)

**Comment by trinacriax** [comment]
Hi, please can you clarify the issue that you are experiencing?
In case you are asking why I used database-cluster is to refer to a cluster of one or more database instances, in my sample I focused on Aurora, as described in the corresponding README

**Comment by radicaldo** [comment]
No, the title is misspelled 😊.  You wrote "dataTase".

Did you mean "dataBase"?



________________________________

**Comment by radicaldo** [comment]
"Database" is misspelled. 

You wrote "DabaTase"

**Comment by trinacriax** [comment]
fixed, thanks
